foreach(i RANGE 1 100)
    math(EXPR div3 "${i} % 3")
    math(EXPR div5 "${i} % 5")
    if (NOT ${div3})
        if (NOT ${div5})
            message(FizzBuzz)
        else()
            message(Fizz)
        endif()
    elseif(NOT ${div5})
        message(Buzz)
    else()
        message(${i})
    endif()
endforeach()
